name: Python CI
on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  linux-x64:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14", "3.13", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: kep3-devel
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
      - name: Build
        run: bash tools/gha_unix_nonmanylinux.sh
        shell: bash -l {0}
        env:
          KEP3_PYTHON_VERSION: ${{ matrix.python-version }}

  linux-arm64:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: kep3-devel
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
      - name: Build
        run: bash tools/gha_unix_nonmanylinux.sh
        shell: bash -l {0}
        env:
          KEP3_PYTHON_VERSION: ${{ matrix.python-version }}

  macos-arm64:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: kep3-devel
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
      - name: Build
        run: bash tools/gha_unix_nonmanylinux.sh
        shell: bash -l {0}
        env:
          KEP3_PYTHON_VERSION: ${{ matrix.python-version }}

  windows-x64:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: kep3-devel
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
      - name: Build
        run: .\tools\gha_windows.ps1
        shell: powershell

  build-and-deploydocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict
      - name: Install and Build docs
        run: bash tools/gha_deploydocs.sh
        shell: bash -l {0}
      - name: Upload to github pages
        if: >-
          github.event_name == 'push' &&
          (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/_build/html
